### ISSUE TITLE
Page Down/Up not working

### ISSUE THREAD

**Issue by catx23** [ONEARMY/precious-plastic#84]
Hi,
in most places the page up & down keys are not working, a little annoying, especially if you have no mouse with wheel. 
Do you have a recommendation where to fix this ? I'm happy to pass a pull request :-)
thanks,
guenter

**Comment by davehakkens** [comment]
weird! Might be in the overflow in the CSS..
Could you share some pages where this occurs?

**Comment by tx4x** [comment]
everywhere except the bazar:
davehakkens.nl & https://davehakkens.nl/community/forums/
but HOME & END keys is working. 
ubuntu & windows 10, chrome & firefox latest
greets,
g

**Comment by zwn** [comment]
I experience the same issue with the page https://davehakkens.nl/community/forums/ and anything bellow. Up/down arrow isn't working either. The rest of the pages seems to be ok.

Tested on firefox & chrome on windows 10.
